spring.application.name=choral-riff
spring.devtools.restart.enabled=false
# server.address=127.0.0.1
server.port=8080

# Attention, "localhost" est à utiliser pour les tests unitaires ave Github Action
# Dans le cas d'utilisation de devcontainers il faut utiliser le nom du conteneur (postgresdb)
# TODO faire d'autres applications.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/choralriffdb

spring.datasource.username=postgres
spring.datasource.password=B@nLgU4qz*9?D~3n83
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JWT Configuration
security.jwt.secret-key=U3VwZXJTZWNyZXRLZXlUaGF0SGFzQXRMZWFzdDMyQ2hhcmFjdGVyczEhIQ==
security.jwt.expiration-time-in-seconds=3600
security.jwt.refresh-expiration-time-in-seconds=604800


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cchoralriff@gmail.com
spring.mail.password=dpem tjng buby janl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


