spring.application.name=choral-riff

spring.datasource.url=jdbc:postgresql://localhost:5432/choralriffdb
spring.datasource.username=choralriff
spring.datasource.password=choralriff
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
